# Generated by Django 3.1.1 on 2024-02-11 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='biodata',
        ),
    ]
