# Generated by Django 3.1.1 on 2024-03-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0002_cheese_country_of_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='Rating',
            field=models.IntegerField(default=0, verbose_name='rating'),
        ),
    ]
