# Generated by Django 3.1.1 on 2024-03-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0003_cheese_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheese',
            name='Rating',
        ),
        migrations.AddField(
            model_name='cheese',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
    ]
