# Generated by Django 3.1.1 on 2024-03-04 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0004_auto_20240304_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheese',
            name='rating',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('cheese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheeses.cheese')),
            ],
        ),
    ]
